import {
  adminArticles,
  adminLaunches,
  adminNews,
  adminSettings,
  adminTimelineEvents,
  adminUsers,
  aiDrafts,
  getAdminDashboardStats,
  managedSources,
  sourceConflicts,
} from "@/data/admin-mock-data"
import type {
  AdminArticle,
  AdminDashboardStats,
  AdminLaunchRecord,
  AdminNewsItem,
  AdminSettings,
  AdminSourceRecord,
  AdminTimelineEvent,
  AdminUser,
  AIDraft,
  AIDraftType,
  ApprovalRecord,
  PublishableStatus,
  SourceConflict,
} from "@/types/admin"
import type { LocalizedText } from "@/types/space"

export interface CreateAIDraftInput {
  type: AIDraftType
  relatedEntityType: AIDraft["relatedEntityType"]
  relatedEntityId: string
  title: LocalizedText
  content: LocalizedText
  citations: AdminSourceRecord[]
  confidenceNotes: LocalizedText
  riskNotes: LocalizedText
}

export interface AdminRepository {
  getDashboardStats(): Promise<AdminDashboardStats>
  listUsers(): Promise<AdminUser[]>
  listLaunches(): Promise<AdminLaunchRecord[]>
  getLaunchById(id: string): Promise<AdminLaunchRecord | undefined>
  listTimelineEvents(launchId: string): Promise<AdminTimelineEvent[]>
  listArticles(): Promise<AdminArticle[]>
  listNews(): Promise<AdminNewsItem[]>
  listSources(): Promise<AdminSourceRecord[]>
  listSourceConflicts(): Promise<SourceConflict[]>
  listAIDrafts(): Promise<AIDraft[]>
  getSettings(): Promise<AdminSettings>
  createAIDraft(input: CreateAIDraftInput): Promise<AIDraft>
  transitionApproval(
    entityId: string,
    status: PublishableStatus,
    userId: string,
    comments?: string
  ): Promise<ApprovalRecord>
}

function clone<T>(value: T): T {
  return structuredClone(value)
}

export const mockAdminRepository: AdminRepository = {
  async getDashboardStats() {
    return clone(getAdminDashboardStats())
  },

  async listUsers() {
    return clone(adminUsers)
  },

  async listLaunches() {
    return clone(adminLaunches)
  },

  async getLaunchById(id) {
    const launch =
      adminLaunches.find((item) => item.id === id) ??
      adminLaunches.find((item) => item.sourceLaunchId === id) ??
      adminLaunches.find((item) => item.slug === id)

    return launch ? clone(launch) : undefined
  },

  async listTimelineEvents(launchId) {
    const launch =
      adminLaunches.find((item) => item.id === launchId) ??
      adminLaunches.find((item) => item.sourceLaunchId === launchId) ??
      adminLaunches.find((item) => item.slug === launchId)

    if (!launch) {
      return []
    }

    return clone(
      adminTimelineEvents
        .filter((event) => event.launchId === launch.sourceLaunchId)
        .sort((a, b) => a.sortOrder - b.sortOrder)
    )
  },

  async listArticles() {
    return clone(adminArticles)
  },

  async listNews() {
    return clone(adminNews)
  },

  async listSources() {
    return clone(managedSources)
  },

  async listSourceConflicts() {
    return clone(sourceConflicts)
  },

  async listAIDrafts() {
    return clone(aiDrafts)
  },

  async getSettings() {
    return clone(adminSettings)
  },

  async createAIDraft(input) {
    const now = new Date().toISOString()

    return {
      id: `ai-draft-${Date.now()}`,
      ...input,
      status: "generated",
      createdBy: "ai_moderator",
      createdAt: now,
      updatedAt: now,
      sourceComparison: [],
      approval: {
        status: "draft",
        submittedBy: "ai-moderator",
        submittedAt: now,
        comments:
          "Generated by the AI Moderator. Human review is mandatory before merge or publish.",
      },
    }
  },

  async transitionApproval(entityId, status, userId, comments) {
    const now = new Date().toISOString()

    return {
      status,
      submittedBy: userId,
      submittedAt: now,
      approvedBy: status === "approved" || status === "published" ? userId : undefined,
      approvedAt: status === "approved" || status === "published" ? now : undefined,
      rejectedBy: status === "archived" ? userId : undefined,
      rejectedAt: status === "archived" ? now : undefined,
      comments:
        comments ??
        `Mock approval transition for ${entityId}. Persist this in a database in production.`,
      diffNotes: "MVP repository returns a transition preview only.",
    }
  },
}

export function getAdminRepository(): AdminRepository {
  // TODO(database): Swap this for a Prisma/Supabase implementation when persistence exists.
  return mockAdminRepository
}
